<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DASpeaker</AssemblyName>
    <Version>1.1.0</Version>
    <ApplicationIcon>Assets\Speaker.ico</ApplicationIcon>
    <RootNamespace>DASpeaker</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>false</SelfContained>
    <PublishSelfContained>false</PublishSelfContained>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Speaker.ico" LogicalName="DASpeaker.Speaker.ico" />
    <InternalsVisibleTo Include="DASpeaker.Tests" />
  </ItemGroup>
</Project>
